pool: Premier Linux Agents

resources:
  repositories:
  - repository: sdlc_templates
    type: github
    name: PremierInc/shield-ado-templates
    endpoint: PremierInc
    
stages:
- template: ci.yaml

- template: deploy.yaml
  parameters:
    stage_name: DEV_DEPLOY
    depends_on: ['ci']
     # set blue_green to False if there is no approvers for the environment or 
     # if you don't want blue_green deployment model
    blue_green: false 
    ado_environment: 'pastahalnp'
    az_subscription_sc: 'SC_ARM_PASTA_NP'
    deploy_variable_group: 'java-app-service-dev'

- template: deploy.yaml
  parameters:
    stage_name: PROD_DEPLOY
    depends_on: ['ci']
     # set blue_green to False if there is no approvers for the environment or 
     # if you don't want blue_green deployment model
    blue_green: true 
    ado_environment: 'pastahalprod'
    az_subscription_sc: 'SC_ARM_PASTA_PROD'
    deploy_variable_group: 'java-app-service-prod'
    # only main and release branch goes to prod
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))
    