stages:
- stage: ci
  jobs:
  - job: Build
    steps:
    - task: Maven@4
      displayName: Maven Build
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        goals: 'clean package'
        options: '-B'
        javaHomeOption: 'Path'
        jdkDirectory: $(SYSTEM_JDK_17)
        mavenVersionOption: 'Path'
        mavenDirectory: $(SYSTEM_MAVEN_3_HOME)

    - bash: mkdir artifacts ; cp target/pasta-bishop-*.jar artifacts/
      displayName: Prepare Artifacts

    - publish: artifacts
      artifact: deploy
      displayName: Publish Artifact
