trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'dacpac_artifact' # Replace with the name of your DACPAC artifact in Azure DevOps
      patterns: '**/*.dacpac'
      targetPath: '$(System.DefaultWorkingDirectory)'

  - script: |
      echo 'Installing SQL Server command-line tools...'
      apt-get update
      apt-get install -y mssql-tools unixodbc-dev
      echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
      source ~/.bashrc

      echo 'Deploying DACPAC to on-premises database...'
      sqlpackage /Action:Publish /SourceFile:$(System.DefaultWorkingDirectory)/*.dacpac /TargetConnectionString:"Data Source=<your_server_name>;Initial Catalog=<your_database_name>;Authentication=ActiveDirectoryIntegrated;"

    displayName: 'Deploy DACPAC'
