name: $(Build.BuildId)_$(Build.SourceBranchName)

# disable trigger
#trigger: none
pr: none

resources:
  repositories:
    - repository: sdlc_templates
      type: github
      name: PremierInc/shield-ado-templates
      endpoint: PremierInc

pool:
  name: 'Premier Linux Agents'

stages:
- template: ci-template.yml

- template: deploy-template.yml
  parameters:
    stage_name: dev
    ado_environment: dev
    service_connection: 'c3duscaui1-scauser'

- template: deploy-template.yml
  parameters:
    stage_name: prod
    ado_environment: PROD
    service_connection: 'c3duscaui1-scauser'
    condition: and(
                succeeded(), 
                eq(variables['Build.SourceBranch'], 'refs/heads/main')
              )
