pool: Premier Linux Agents

stages:
- template: ci.yaml 

- template: deploy.yaml
  parameters:
    stage_name: DEV_DEPLOY
    depends_on: ['ci']
     # set blue_green to False if there is no approvers for the environment or 
     # if you don't want blue_green deployment model
    blue_green: false 
    ado_environment: 'cqdoc-provision-dev'
    az_acr_sc: "SC_ACR_cqdocdevacr"
    az_subscription_sc: "SC_ARM_SUB_CQDOC_NP"
    az_app_service: 'cqdocprovisiondev'
    az_app_service_rg: "cqdocDEVLinuxPlanRG"
    az_acr_registry_url: 'cqdocdevacr.azurecr.io'
    deploy_variable_group: 'cqdoc-provision-dev-azure'

- template: deploy.yaml
  parameters:
    stage_name: QA_DEPLOY
    depends_on: ['ci']
    # main and develop goes to QA
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/develop'))
    # set blue_green to False if there is no approvers for the environment or 
    # if you don't want blue_green deployment model
    blue_green: false
    ado_environment: 'cqdoc-provision-qa'
    az_acr_sc: "SC_ACR_cqdocqaacr"
    az_subscription_sc: "SC_ARM_SUB_CQDOC_NP"
    az_app_service: 'cqdocprovisionqa'
    az_app_service_rg: "cqdocQALinuxPlanRG"
    az_acr_registry_url: 'cqdocqaacr.azurecr.io'
    deploy_variable_group: 'cqdoc-provision-qa-azure'

- template: deploy.yaml
  parameters:
    stage_name: UAT_DEPLOY
    depends_on: ['ci']
    # main, release goes to uat
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))
    # set blue_green to False if there is no approvers for the environment or 
    # if you don't want blue_green deployment model
    blue_green: true
    ado_environment: 'cqdoc-provision-uat'
    az_acr_sc: "SC_ACR_cqdocuatacr"
    az_subscription_sc: "SC_ARM_SUB_CQDOC_PROD"
    az_app_service: 'cqdocprovisionuat'
    az_app_service_rg: "cqdocUATLinuxPlanRG"
    az_acr_registry_url: 'cqdocuatacr.azurecr.io'
    deploy_variable_group: 'cqdoc-provision-uat-azure'

- template: deploy.yaml
  parameters:
    stage_name: PROD_DEPLOY
    depends_on: ['ci']
    # main and release goes to prod 
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))
    # set blue_green to False if there is no approvers for the environment or 
    # if you don't want blue_green deployment model
    blue_green: false 
    ado_environment: 'cqdoc-provision-prod'
    az_acr_sc: "SC_ACR_cqdocprodacr"
    az_subscription_sc: "SC_ARM_SUB_CQDOC_PROD"
    az_app_service: 'cqdocprovisionprod'
    az_app_service_rg: "cqdocPRODLinuxPlanRG"
    az_acr_registry_url: 'cqdocprodacr.azurecr.io'
    deploy_variable_group: 'cqdoc-provision-prod-azure'
